{{ if .Values.ingestion.enabled }}
{{ if not .Values.ingestion.collections.configMap }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: config-operator
    namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}

