apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-serviceaccount
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-serviceaccount-role-binding
subjects:
- kind: ServiceAccount
  name: spark-serviceaccount
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io